ver: 1
firebase:
  apiKey: "AIzaSyD0ZowaJDI5_g8_xF1ZaABXXKz0wLYjJGs"
  authDomain: "tkame123-othello-dev.firebaseapp.com"
  databaseURL: "https://tkame123-othello-dev.firebaseio.com"
  projectId: "tkame123-othello-dev"
  storageBucket: "tkame123-othello-dev.appspot.com"
  messagingSenderId: "81835539134"
  appId: "1:81835539134:web:2b6cd6bed683396fc07cef"
sentry:
  sentryDsn: "https://6b6b01f85cfa408da6a4cfa053e0984b@sentry.io/1550122"
appNotificationMessages:
  maxNotificationMessages: 10
  delayMessageMilliiSeconds: 5000
board:
  size: 4
style:
  color:
    border: "#eee"
    primary: "#3F51B5"
    primaryDark: "#303F9F"
    primaryLight: "#9FA8DA"
    secondary: "#80DEEA"
    secondaryDark: "#26C6DA"
    secondaryLight: "#E0F7FA"
    background: "#FFFFFF"
    surface: "#FFFFFF"
    error: "#B00020"
    onPrimary: "#FFFFFF"
    onSecondary: "#000000"
    onBackground: "#000000"
    onsurface: "#000000"
    onError: "#FFFFFF"
  zindex:
    defaultModal: 30
    nav: 20
    notification: 15
    progress: 10
