ver: 1
firebase:
  apiKey: "AIzaSyA-HNBbbY0JycbfOtRykX8UTpTmX263SE0"
  authDomain: "tkame123-othello.firebaseapp.com"
  databaseURL: "https://tkame123-othello.firebaseio.com"
  projectId: "tkame123-othello"
  storageBucket: "tkame123-othello.appspot.com"
  messagingSenderId: "650086036833"
  appId: "1:650086036833:web:100a41fb2683c527"
sentry:
  sentryDsn: "https://6b6b01f85cfa408da6a4cfa053e0984b@sentry.io/1550122"
appNotificationMessages:
  maxNotificationMessages: 10
  delayMessageSeconds: 5
board:
  size: 4
style:
  color:
    general: "#d50080"
  zindex:
    progress: 999
